In [2]:
import numpy as np
import scipy
from scipy import linalg

In [3]:
Q=np.fromstring("-1.4651 1.3374 0.1277 0 1.2154 -1.2220 0.0066 0 0.0099 0.0808 -0.5993 0.5086 0 0 0.8530 -0.8530", dtype=float, sep=" ").reshape(4,4)
Q

array([[-1.4651,  1.3374,  0.1277,  0.    ],
       [ 1.2154, -1.222 ,  0.0066,  0.    ],
       [ 0.0099,  0.0808, -0.5993,  0.5086],
       [ 0.    ,  0.    ,  0.853 , -0.853 ]])

In [25]:
stationary_mat = linalg.expm(Q*1000)
stationary_mat

In [29]:
sum_i_total = np.zeros_like(Q)
for i in range(Q.shape[0]):
    sum_i=Q[i,i] * stationary_mat[i]
    sum_i_total += sum_i
print(-1*sum_i_total)

[[0.90393832 1.07864354 1.3511794  0.80563874]
 [0.90393832 1.07864354 1.3511794  0.80563874]
 [0.90393832 1.07864354 1.3511794  0.80563874]
 [0.90393832 1.07864354 1.3511794  0.80563874]]
