# Method to Determine Eigenvectors and Eigenvalues for Q

In [3]:
#These are the EigenVectors and Eigen Values Q

import numpy as np

Q = np.mat("0 0.121 0.1864 0.337 0.0631 0.158; 0.148 0 0.3739 0.1349 0.0632 0.1582; 0.1461 0.2398 0 0.1333 0.4073 0.1558; 0.3692 0.1209 0.1863 0 0.0947 0.2368; 0.1468 0.1203 1.2085 0.201 0 0.2359; 0.1471 0.1205 0.185 0.2012 0.0944 0")
print("Q : /n", Q)

print("Eigenvlaues :", np.linalg.eigvals(Q))

eigenvalue,eigenvector = np.linalg.eig(Q)

print("Eigenvectors:", eigenvector)

Q : /n [[0.     0.121  0.1864 0.337  0.0631 0.158 ]
 [0.148  0.     0.3739 0.1349 0.0632 0.1582]
 [0.1461 0.2398 0.     0.1333 0.4073 0.1558]
 [0.3692 0.1209 0.1863 0.     0.0947 0.2368]
 [0.1468 0.1203 1.2085 0.201  0.     0.2359]
 [0.1471 0.1205 0.185  0.2012 0.0944 0.    ]]
Eigenvlaues : [ 1.0875624  -0.73617136  0.23732603 -0.36128127 -0.1420708  -0.08536501]
Eigenvectors: [[ 0.28710999  0.04290567  0.46136169 -0.63615448  0.40084388  0.17589605]
 [ 0.30739469  0.19232918  0.05956636  0.08476569  0.24288162 -0.865512  ]
 [ 0.43716967 -0.52342231 -0.31186057 -0.02886221  0.0809903   0.01622366]
 [ 0.32323948 -0.02464578  0.48461299  0.74519149  0.11134992  0.22228956]
 [ 0.67591782  0.8285685  -0.6301251   0.02758735 -0.01777006  0.40345384]
 [ 0.26572614 -0.00803087  0.23330845 -0.17668562 -0.87238678 -0.08659509]]


# Method to detemine the Eigenvalue decomposition of Q

In [6]:
# This is the EigenValue Decomposition of Q

u, V = np.linalg.eig(Q)

print(np.dot(V,np.dot(np.diag(u), np.linalg.inv(V))))
print()
print()
print()

print(u)

[[ 8.32667268e-17  1.21000000e-01  1.86400000e-01  3.37000000e-01
   6.31000000e-02  1.58000000e-01]
 [ 1.48000000e-01  1.52655666e-16  3.73900000e-01  1.34900000e-01
   6.32000000e-02  1.58200000e-01]
 [ 1.46100000e-01  2.39800000e-01 -7.21644966e-16  1.33300000e-01
   4.07300000e-01  1.55800000e-01]
 [ 3.69200000e-01  1.20900000e-01  1.86300000e-01  1.38777878e-16
   9.47000000e-02  2.36800000e-01]
 [ 1.46800000e-01  1.20300000e-01  1.20850000e+00  2.01000000e-01
   5.55111512e-17  2.35900000e-01]
 [ 1.47100000e-01  1.20500000e-01  1.85000000e-01  2.01200000e-01
   9.44000000e-02 -2.35922393e-16]]



[ 1.0875624  -0.73617136  0.23732603 -0.36128127 -0.1420708  -0.08536501]


In [8]:
eigenvector_inv = np.linalg.inv(eigenvector)
print(eigenvector_inv)

Q_values = np.mat("1.0875624 0 0 0 0 0; 0 -0.73617136 0 0 0 0; 0 0 0.23732603 0 0 0; 0 0 0 -0.36128127 0 0; 0 0 0 0 -0.1420708 0; 0 0 0 0 0 -0.08536501")
print(Q_values)

S_i = eigenvector*Q_values*eigenvector_inv
print()
print()
print()



print(S_i)

[[ 0.37232675  0.32609711  0.72314732  0.38257685  0.37681871  0.37015648]
 [ 0.06321434  0.23228338 -0.9857207  -0.0331247   0.5259022  -0.01273645]
 [ 0.58899657  0.06203076 -0.50780358  0.56473636 -0.34578918  0.31988413]
 [-0.66793167  0.07274679 -0.03877714  0.71423387  0.01251784 -0.19933887]
 [ 0.38290738  0.19066989  0.09873509  0.09695451 -0.00751026 -0.89556354]
 [ 0.22885538 -0.92305251  0.02675266  0.26453883  0.22601418 -0.12018798]]
[[ 1.0875624   0.          0.          0.          0.          0.        ]
 [ 0.         -0.73617136  0.          0.          0.          0.        ]
 [ 0.          0.          0.23732603  0.          0.          0.        ]
 [ 0.          0.          0.         -0.36128127  0.          0.        ]
 [ 0.          0.          0.          0.         -0.1420708   0.        ]
 [ 0.          0.          0.          0.          0.         -0.08536501]]



[[-1.96554309e-09  1.20999999e-01  1.86400000e-01  3.37000000e-01
   6.31000003e-02  1.58000000

In [12]:
def I_ij_calculation_method(rate_i, time, rate_j):
    if rate_i == rate_j:
        I_ij = time*exp(rate_i*time)
    else: 
        I_ij = (exp(rate_i*time)-exp(rate_j*time))/(rate_i - rate_j)
    
    return I_ij

In [13]:
m= Q.shape[0]

In [14]:
m

6

In [18]:
E = np.zeros((m,m))

In [20]:
E[1,1] = 1

In [21]:
E

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
for i in range(m):
    E_i = np.zeros((m,m))
    E_i[i,i]=1
    
    print("print i", i)
    print(E_i)
    S_i = eigenvector*E_i*eigenvector_inv
    print("print S_i", S_i)
    for j in range(m):
        E_j = np.zeros((m,m))
        E_j[j,j]=1
        S_j= eigenvector*E_j*eigenvector_inv
        print("j equals", j)
        print(E_j)
        print("print S_j", S_j)

print i 0
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
print S_i [[0.10689873 0.09362574 0.20762282 0.10984164 0.10818842 0.10627562]
 [0.11445127 0.10024052 0.22229165 0.11760209 0.11583207 0.11378414]
 [0.16276996 0.14255977 0.31613808 0.167251   0.16473371 0.16182119]
 [0.1203507  0.10540746 0.23374976 0.12366394 0.12180268 0.11964919]
 [0.25166228 0.22041485 0.48878816 0.25859051 0.25469848 0.25019536]
 [0.09893695 0.08665252 0.19215914 0.10166067 0.10013058 0.09836025]]
j equals 0
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
print S_j [[0.10689873 0.09362574 0.20762282 0.10984164 0.10818842 0.10627562]
 [0.11445127 0.10024052 0.22229165 0.11760209 0.11583207 0.11378414]
 [0.16276996 0.14255977 0.31613808 0.167251   0.16473371 0.16182119]
 [0.1203507  0.10540746 0.23374976 0.12366394 0.12180268 0.11964919]
 [0.25166228 0