# Method to Determine Eigenvectors and Eigenvalues for Q

In [1]:
#These are the EigenVectors and Eigen Values Q

import numpy as np

Q = np.mat("0 0.121 0.1864 0.337 0.0631 0.158; 0.148 0 0.3739 0.1349 0.0632 0.1582; 0.1461 0.2398 0 0.1333 0.4073 0.1558; 0.3692 0.1209 0.1863 0 0.0947 0.2368; 0.1468 0.1203 1.2085 0.201 0 0.2359; 0.1471 0.1205 0.185 0.2012 0.0944 0")
print("Q : /n", Q)

print("Eigenvlaues :", np.linalg.eigvals(Q))

eigenvalue,eigenvector = np.linalg.eig(Q)

print("Eigenvectors:", eigenvector)

Q : /n [[0.     0.121  0.1864 0.337  0.0631 0.158 ]
 [0.148  0.     0.3739 0.1349 0.0632 0.1582]
 [0.1461 0.2398 0.     0.1333 0.4073 0.1558]
 [0.3692 0.1209 0.1863 0.     0.0947 0.2368]
 [0.1468 0.1203 1.2085 0.201  0.     0.2359]
 [0.1471 0.1205 0.185  0.2012 0.0944 0.    ]]
Eigenvlaues : [ 1.0875624  -0.73617136  0.23732603 -0.36128127 -0.1420708  -0.08536501]
Eigenvectors: [[ 0.28710999  0.04290567  0.46136169 -0.63615448  0.40084388  0.17589605]
 [ 0.30739469  0.19232918  0.05956636  0.08476569  0.24288162 -0.865512  ]
 [ 0.43716967 -0.52342231 -0.31186057 -0.02886221  0.0809903   0.01622366]
 [ 0.32323948 -0.02464578  0.48461299  0.74519149  0.11134992  0.22228956]
 [ 0.67591782  0.8285685  -0.6301251   0.02758735 -0.01777006  0.40345384]
 [ 0.26572614 -0.00803087  0.23330845 -0.17668562 -0.87238678 -0.08659509]]


In [2]:
eigenvalue

array([ 1.0875624 , -0.73617136,  0.23732603, -0.36128127, -0.1420708 ,
       -0.08536501])

# Method to detemine the Eigenvalue decomposition of Q

In [3]:
# This is the EigenValue Decomposition of Q

u, V = np.linalg.eig(Q)

print(np.dot(V,np.dot(np.diag(u), np.linalg.inv(V))))
print()
print()
print()

print(u)

[[ 8.32667268e-17  1.21000000e-01  1.86400000e-01  3.37000000e-01
   6.31000000e-02  1.58000000e-01]
 [ 1.48000000e-01  1.52655666e-16  3.73900000e-01  1.34900000e-01
   6.32000000e-02  1.58200000e-01]
 [ 1.46100000e-01  2.39800000e-01 -7.21644966e-16  1.33300000e-01
   4.07300000e-01  1.55800000e-01]
 [ 3.69200000e-01  1.20900000e-01  1.86300000e-01  1.38777878e-16
   9.47000000e-02  2.36800000e-01]
 [ 1.46800000e-01  1.20300000e-01  1.20850000e+00  2.01000000e-01
   5.55111512e-17  2.35900000e-01]
 [ 1.47100000e-01  1.20500000e-01  1.85000000e-01  2.01200000e-01
   9.44000000e-02 -2.35922393e-16]]



[ 1.0875624  -0.73617136  0.23732603 -0.36128127 -0.1420708  -0.08536501]


In [4]:
eigenvector_inv = np.linalg.inv(eigenvector)
print(eigenvector_inv)

Q_values = np.mat("1.0875624 0 0 0 0 0; 0 -0.73617136 0 0 0 0; 0 0 0.23732603 0 0 0; 0 0 0 -0.36128127 0 0; 0 0 0 0 -0.1420708 0; 0 0 0 0 0 -0.08536501")
print(Q_values)

S_i = eigenvector*Q_values*eigenvector_inv
print()
print()
print()



print(S_i)

[[ 0.37232675  0.32609711  0.72314732  0.38257685  0.37681871  0.37015648]
 [ 0.06321434  0.23228338 -0.9857207  -0.0331247   0.5259022  -0.01273645]
 [ 0.58899657  0.06203076 -0.50780358  0.56473636 -0.34578918  0.31988413]
 [-0.66793167  0.07274679 -0.03877714  0.71423387  0.01251784 -0.19933887]
 [ 0.38290738  0.19066989  0.09873509  0.09695451 -0.00751026 -0.89556354]
 [ 0.22885538 -0.92305251  0.02675266  0.26453883  0.22601418 -0.12018798]]
[[ 1.0875624   0.          0.          0.          0.          0.        ]
 [ 0.         -0.73617136  0.          0.          0.          0.        ]
 [ 0.          0.          0.23732603  0.          0.          0.        ]
 [ 0.          0.          0.         -0.36128127  0.          0.        ]
 [ 0.          0.          0.          0.         -0.1420708   0.        ]
 [ 0.          0.          0.          0.          0.         -0.08536501]]



[[-1.96554309e-09  1.20999999e-01  1.86400000e-01  3.37000000e-01
   6.31000003e-02  1.58000000

In [5]:
def I_ij_calculation_method(rate_i, time, rate_j):
    if rate_i == rate_j:
        I_ij = time*exp(rate_i*time)
    else: 
        I_ij = (exp(rate_i*time)-exp(rate_j*time))/(rate_i - rate_j)
    
    return I_ij

In [6]:
m= Q.shape[0]

In [7]:
m

6

In [8]:
E = np.zeros((m,m))

In [9]:
E[1,1] = 1

In [10]:
E

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
def expected_number_of_transitions_in_time_t(t):  
    E_n = np.zeros((m,m))
    for i in range(m):
        d_i=eigenvalue[i]
        E_i = np.zeros((m,m))
        E_i[i,i]=1


        S_i = eigenvector*E_i*eigenvector_inv
        
        for j in range(m):
            d_j=eigenvalue[j]
            E_j = np.zeros((m,m))
            E_j[j,j]=1
            S_j= eigenvector*E_j*eigenvector_inv
           
            if d_i == d_j:
                I_ij = t*np.exp(d_i*t)
            else: 
                I_ij = (np.exp(d_i*t)-np.exp(d_j*t))/(d_i - d_j)

            N_greek=S_i*Q*S_j*I_ij
            E_n += N_greek
         
    return E_n


In [12]:
expected_number_of_transitions_in_time_t(1)

array([[0.29671631, 0.32216739, 0.60292535, 0.53928089, 0.29240695,
        0.4015138 ],
       [0.39390026, 0.23894032, 0.77472723, 0.39165344, 0.34720075,
        0.39666954],
       [0.47266168, 0.49686286, 0.88455883, 0.48446971, 0.66095034,
        0.49744687],
       [0.59084211, 0.35101495, 0.67711223, 0.34118033, 0.34100175,
        0.48440126],
       [0.68017038, 0.66072331, 1.96112697, 0.72391751, 0.7265436 ,
        0.75363261],
       [0.37379798, 0.30209813, 0.59069936, 0.41158173, 0.30160222,
        0.2338341 ]])

In [13]:
expected_number_of_transitions_in_time_t(2)

array([[2.06565935, 1.83449652, 3.79334825, 2.44693295, 1.93999097,
        2.18310751],
       [2.24268549, 1.78010259, 4.29680167, 2.28637133, 2.19627797,
        2.23160493],
       [2.97385572, 2.75566119, 5.99789678, 3.06726565, 3.32933675,
        3.03399921],
       [2.68098238, 2.04921188, 4.28686094, 2.37899537, 2.19850387,
        2.48652594],
       [4.51265559, 4.17935483, 9.87861144, 4.66740662, 4.88283224,
        4.64607836],
       [2.0323786 , 1.69949305, 3.60279278, 2.11271819, 1.85938863,
        1.75939457]])

In [14]:
import seaborn as sns
print(sns.heatmap(expected_number_of_transitions_in_time_t(2),annot=True))

AxesSubplot(0.125,0.11;0.62x0.77)


In [15]:
def expected_number_of_transitions_in_time_t(t, Q):  
    m= Q.shape[0]
    eigenvalue,eigenvector = np.linalg.eig(Q)
    eigenvector_inv = np.linalg.inv(eigenvector)
    E_n = np.zeros((m,m))
    for i in range(m):
        d_i=eigenvalue[i]
        E_i = np.zeros((m,m))
        E_i[i,i]=1


        S_i = eigenvector*E_i*eigenvector_inv
        
        for j in range(m):
            d_j=eigenvalue[j]
            E_j = np.zeros((m,m))
            E_j[j,j]=1
            S_j= eigenvector*E_j*eigenvector_inv
           
            if d_i == d_j:
                I_ij = t*np.exp(d_i*t)
            else: 
                I_ij = (np.exp(d_i*t)-np.exp(d_j*t))/(d_i - d_j)

            N_greek=S_i*Q*S_j*I_ij
            E_n += N_greek
         
    return E_n