In [7]:
import numpy as np

Q = np.mat("0 0.121 0.1864 0.337 0.0631 0.158; 0.148 0 0.3739 0.1349 0.0632 0.1582; 0.1461 0.2398 0 0.1333 0.4073 0.1558; 0.3692 0.1209 0.1863 0 0.0947 0.2368; 0.1468 0.1203 1.2085 0.201 0 0.2359; 0.1471 0.1205 0.185 0.2012 0.0944 0")
print("Q : /n", Q)

print("Eigenvlaues :", np.linalg.eigvals(Q))

eigenvalue,eigenvector = np.linalg.eig(Q)

print("Eigenvectors:", eigenvector)

Q : /n [[0.     0.121  0.1864 0.337  0.0631 0.158 ]
 [0.148  0.     0.3739 0.1349 0.0632 0.1582]
 [0.1461 0.2398 0.     0.1333 0.4073 0.1558]
 [0.3692 0.1209 0.1863 0.     0.0947 0.2368]
 [0.1468 0.1203 1.2085 0.201  0.     0.2359]
 [0.1471 0.1205 0.185  0.2012 0.0944 0.    ]]
Eigenvlaues : [ 1.0875624  -0.73617136  0.23732603 -0.36128127 -0.1420708  -0.08536501]
Eigenvectors: [[ 0.28710999  0.04290567  0.46136169 -0.63615448  0.40084388  0.17589605]
 [ 0.30739469  0.19232918  0.05956636  0.08476569  0.24288162 -0.865512  ]
 [ 0.43716967 -0.52342231 -0.31186057 -0.02886221  0.0809903   0.01622366]
 [ 0.32323948 -0.02464578  0.48461299  0.74519149  0.11134992  0.22228956]
 [ 0.67591782  0.8285685  -0.6301251   0.02758735 -0.01777006  0.40345384]
 [ 0.26572614 -0.00803087  0.23330845 -0.17668562 -0.87238678 -0.08659509]]
